"""initial

Revision ID: 54c55c7f095f
Revises: 
Create Date: 2026-03-06 23:21:19.222163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54c55c7f095f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=False),
    sa.Column('imap_host', sa.String(length=255), nullable=False),
    sa.Column('imap_port', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_address')
    )
    op.create_table('labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('condition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emails',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.String(length=512), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('imap_uid', sa.BigInteger(), nullable=True),
    sa.Column('imap_folder', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('sender', sa.String(length=512), nullable=True),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('recipients', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reply_to', sa.String(length=512), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('raw_headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('has_attachments', sa.Boolean(), nullable=False),
    sa.Column('list_unsubscribe', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'account_id', name='uq_email_message_account')
    )
    op.create_index('ix_emails_account_id', 'emails', ['account_id'], unique=False)
    op.create_index('ix_emails_received_at', 'emails', ['received_at'], unique=False)
    op.create_index('ix_emails_sender', 'emails', ['sender'], unique=False)
    op.create_table('email_classifications',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email_id', sa.BigInteger(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('method', sa.Enum('rule', 'ml', 'manual', name='classificationmethod'), nullable=False),
    sa.Column('is_overridden', sa.Boolean(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('classified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_id', 'method', name='uq_classification_email_method')
    )
    op.create_index('ix_classifications_label_id', 'email_classifications', ['label_id'], unique=False)
    op.create_table('unsubscribe_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email_id', sa.BigInteger(), nullable=False),
    sa.Column('method', sa.Enum('mailto', 'https', name='unsubscribemethod'), nullable=False),
    sa.Column('url_or_address', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'success', 'failed', 'skipped', name='unsubscribestatus'), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unsubscribe_log')
    op.drop_index('ix_classifications_label_id', table_name='email_classifications')
    op.drop_table('email_classifications')
    op.drop_index('ix_emails_sender', table_name='emails')
    op.drop_index('ix_emails_received_at', table_name='emails')
    op.drop_index('ix_emails_account_id', table_name='emails')
    op.drop_table('emails')
    op.drop_table('rules')
    op.drop_table('labels')
    op.drop_table('accounts')
    # ### end Alembic commands ###
